##################################################################################################
# Bosch Indego Mower package                                                                     #
# Version 0.1 last updated 2020-07-23                                                            #
# Created for and tested with Home Assistant Hassio version 0.113                                #
# Creator Jens Mazzanti-Myretyr                                                                  #
# Dependencies:                                                                                  #
# https://github.com/jm-73/Indego                                                                #
##################################################################################################

# Automation section
automation:
  - id: '1221567890121'
    alias: "Indego: mow"
    initial_state: true
    trigger:
      - platform: time
        at: "10:15:00"
    condition:
      - condition: and
        conditions:
          - condition: time
            weekday:
              - mon
              - wed
              - thu
              - fri
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.autoindego_lawnstatus
            state: "on"
    action:
      - service: indego.command
        data:
          command: mow

  - id: '1221567890122'
    alias: "Indego: stop mow on time"
    initial_state: true
    trigger:
      - platform: time
        at: "18:00:00"
    condition:
      - condition: and
        conditions:
          - condition: time
            weekday:
              - mon
              - wed
              - thu
              - fri
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.autoindego_lawnstatus
            state: "on"
    action:
      - service: indego.command
        data:
          command: returnToDock

  - id: '1221567890123'
    alias: "Indego: stop mow when 100% done"
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.autoindego_mow_session_completed
        from: "off"
        to: "on"
    action:
      - service: indego.command
        data:
          command: returnToDock
      - service: homeassistant.turn_off
        entity_id: input_boolean.autoindego_mow_session_completed

  - id: '1221567890124'
    alias: "Indego_system: check when completed flips over 100%"
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: "/1"
    condition:
      - condition: numeric_state
        entity_id:
          - sensor.indego_505703041_lawm_mowed
        below: "50"
      - condition: state
        entity_id: input_boolean.autoindego_completed_upper
        state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.autoindego_completed_upper
      - service: homeassistant.turn_on
        entity_id: input_boolean.autoindego_mow_session_completed

  - id: '1221567890125'
    alias: "Indego_system: check completed upper"
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: "/1"
    condition:
      - condition: numeric_state
        entity_id:
          - sensor.indego_505703041_lawm_mowed
        above: "50"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.autoindego_completed_upper

#Lightning
  - id: '1221567890140'
    alias: "Indego_system: lightning protection trigger"
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightning_counter
        above: 1
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.autoindego_lightning_protect

  - id: '1221567890141'
    alias: "Indego_system: lightning protection de-trigger"
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightning_counter
        below: 1
    action:
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.autoindego_lightning_protect


  - id: '1221567890130'
    alias: "Indego_system: lightning protection"
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.lightning_protect
        from: "off"
        to: "on"
    action:
      - service: indego.command
        data:
          command: mow
      - delay:
          minutes: 1
      - service: indego.command
        data:
          command: pause

  - id: '1221567890131'
    alias: "Indego_system: lightning protection stop"
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.autoindego_lightning_protect
        from: "on"
        to: "off"
    action:
      - service: indego.command
        data:
          command: returnToDock

# Bolean section
input_boolean:
  autoindego_lawn_icon:
    name: Test grass icon
    initial: on
    icon: mdi:grass
  autoindego_lawnstatus:
    name: Lawn cleared
    initial: on
    icon: mdi:traffic-light
  autoindego_completed_upper:
    name: Lawn over 50%
    initial: off
    icon: mdi:arrow-collapse-up
  autoindego_mow_session_completed:
    name: Mow session completed
    initial: off
    icon: mdi:check-outline
  autoindego_lightning_protect:
    name: Lightning protect
    initial: off
    icon: mdi:weather-lightning
  autoindego_rain_protect:
    name: Rain protect
    initial: off
    icon: mdi:weather-pouring

sensor:
  ### Place your lightning sensor here. Either local sensor or cloud based services.
  - platform: template
    sensors:
      autoindego_lightning_counter:
        value_template: "{{states.sensor.blitzortung_lightning_counter.state}}"

  ### Place your rain sensor here. Either local sensor or cloud based services.
  - platform: template
    sensors:
      autoindego_rain_counter:
        #value_template: "{{states.sensor.rain_counter.state}}"
        value_template: "{{states.weathertest_precipitation.state}}"
        #sensor.weathertest_precipitation

#  - platform: openweathermap
#    api_key: 6657306f1b4a0779a3fbf787c69c4007
#    monitored_conditions:
#      - rain